name: Tunehub-Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push Docker Image to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Install Java and Maven
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - name: building jar file
        run: mvn -f ProjectTuneHub/pom.xml clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/tunehub:latest -f ProjectTuneHub/Dockerfile ProjectTuneHub
        
      - name: Log in to DockerHub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/tunehub:latest

  deploy:
    name: Deploy Application to EC2 Server
    runs-on: self-hosted
    needs: build

    steps:
      - name: Create Docker Network
        run: docker network create musichub-network || true

      - name: Run MySQL Container
        run: |
          docker run -d --name tunehub-db \
          --network musichub-network \
          -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          -e MYSQL_DATABASE=${{ vars.MYSQL_DATABASE }} \
          -e MYSQL_USER=${{ vars.MYSQL_USER }} \
          -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
          -p 3306:3306 \
          mysql:latest
      - name: Wait for MySQL readiness
        run: |
          until docker exec tunehub-db mysqladmin ping -h "localhost" --silent; do
          echo "Waiting for MySQL..."
          sleep 5
          done



      - name: Pull TuneHub Image
        run: docker pull ${{ vars.DOCKERHUB_USERNAME }}/tunehub:latest

      - name: Run TuneHub App
        run: |
          docker run -d \
          --name tunehub-app \
          --network musichub-network \
          -e SPRING_DATASOURCE_URL=jdbc:mysql://tunehub-db:3306/${{ vars.MYSQL_DATABASE }} \
          -e SPRING_DATASOURCE_USERNAME=${{ vars.MYSQL_USER }} \
          -e SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
          -e SERVER_PORT=8080 \
          -p 8080:8080 \
          ${{ vars.DOCKERHUB_USERNAME }}/tunehub:latest

      - name: Check Running Containers
        run: docker ps -a

